apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-api-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  JWT_ISSUER: FiapCloudGames
  JWT_AUDIENCE: FiapCloudGamesClients
  RABBITMQ_HOST: rabbitmq
